target 'iosApp' do
  use_frameworks!
  platform :ios, '14.1'
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesCombine', '1.0.0-ALPHA-5'
  pod 'KMPNativeCoroutinesAsync', '1.0.0-ALPHA-5'
end
